### ISSUE TITLE
界面中文问题（两个问题）

### ISSUE THREAD

**Issue by 17-qxm** [hezex/hep#10]
# 1.英文情况下中文显示问题
在`hep -help`的返回内容中存在以下问题：

> Note that the suffix numbers of the data files MUST be consecutive from 1
'-' options:
-?/-help        Get more information about hep.exe. You can add -- as a suffix t
o choose the language of the help document. The languages we've finished transla
ting are:
 --en-us        English
 --zn-ch        涓枃
-clear          Delete every file in folder "UnacceptedData". 

其中的倒数第二行出现了问题。
把`./bin/text/help.txt`更改为用`ANSI编码`保存问题可以解决。

# 2.中文调节问题
在`hep -help`的返回内容中存在以下问题：

> Note that the suffix numbers of the data files MUST be consecutive from 1
'-' options:
-?/-help        Get more information about hep.exe. You can add -- as a suffix t
o choose the language of the help document. The languages we've finished transla
ting are:
 --en-us        English
 --zn-ch        涓枃
-clear          Delete every file in folder "UnacceptedData". 

其中的倒数第二行出现了问题。
使用`hep -help--zn-ch`无法调节至中文，然而在源代码文件（`./hep 1.0.cpp`）中的第25行及以下行数中，出现了如下代码：
>else if(!strcmp(argv[1],"-help--cn-zh")||!strcmp(argv[1],"-?--cn-zh"))//这一行判断有问题！！！
{
	print_from_file("help cn-zh.txt");
	return 0;
}

你他妈认真的吗？分清楚`cn-zh`和`zn-ch`好不好？

**Comment by hezex** [comment]
Got it and have been fixed.
We will release the pack at next update.
